import Head from 'next/head';
import { ReactNode } from 'react';
import Header from './Header';

export default function Layout({
  title,
  children,
}: {
  title?: string;
  children: ReactNode;
}) {
  return (
    <>
      <Head>
        <title>INFO | {title ? title : 'INFO'}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main>{children}</main>
    </>
  );
}
