import { InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { getAlbums } from '../queries/albumQuery';

export default function Home({
  albums,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div>
      <Head>
        <title>INFO</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>INFO</h1>
        {albums.map(({ title, artist, slug, artwork }) => (
          <div key={slug}>
            <Image
              className='w-32 h-32'
              src={artwork.url}
              alt={artwork.title}
              width={artwork.width}
              height={artwork.height}
            />
            <h2>
              <span>{artist}</span>
              <br />
              <span>{title}</span>
            </h2>
          </div>
        ))}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      albums: await getAlbums(),
    },
    revalidate: 60 * 60,
  };
}
