import { InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Header from '../components/Header';
import { getReleases } from '../queries/Releases';

export default function Home({
  releases,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div>
      <Head>
        <title>INFO</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <main>
        <div className='grid md:grid-cols-2 m-4'>
          {releases.map(({ title, artist, slug, artwork }) => (
            <Link href={`/releases/${slug}`} key={slug}>
              <div>
                <Image
                  className='w-full h-auto'
                  src={artwork.url}
                  alt={artwork.title}
                  width={artwork.width}
                  height={artwork.height}
                />
                <h2>
                  <span>{artist}</span>
                  <br />
                  <span>{title}</span>
                </h2>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      releases: await getReleases(),
    },
    revalidate: 60 * 60,
  };
}
